create database customer_behaviour ;

use customer_behaviour;

select * from customer limit 20;

-- Q1. What is the total revenue generated by male vs. female customers?

select gender,
sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
 select * from customer;

select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?
select * from customer;

select item_purchased, round(avg(review_rating),2) as avg_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select * from customer;

select shipping_type,
round(avg(purchase_amount),2) 
from customer
where shipping_type IN ('Standard', 'Express') 
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.  

select * from customer;

select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select * from customer;

select item_purchased,
round(100*sum(case when discount_applied = "Yes" Then  1 ELse 0 End)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5 ;	

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

select * from customer;

with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 Then "New"
    when previous_purchases between 2 and 10 Then "Returing"
    else "Loyal"
    end as customer_segment
from customer
)
select customer_segment,count(*) as Number_of_customer
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 

select * from customer;

with top_purchase as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc ) as item_rank
from customer
group by category ,item_purchased
)
select item_rank, category,item_purchased,total_orders
from top_purchase  
where item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select * from customer;

select subscription_status,
count(customer_id) as repeat_buyer
from customer
where previous_purchases >5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select * from customer;

select age_group,
sum(purchase_amount) as total_amount
from customer
group by age_group
order by total_amount desc
